### ISSUE TITLE
Nesting is lost when combining `and` and `or`, and when combining with `NOTNULL`

### ISSUE THREAD

**Issue by tarsius** [skeeto/emacsql#16]
I wrote `[:where (and (= a "a") (or (= b "b") (= b "B")))`
and expected `WHERE a = '"a"' AND ( b = '"b"' OR b = '"B"' );`
but got `WHERE a = '"a"' AND b = '"b"' OR b = '"B"';`

----

And once that works, how do I get `WHERE a NOTNULL AND ( b = '"b"' OR b = '"B"');`?

Using `[:where (and a :notnull (or (= b "b") (= b "B")))]`
I get `WHERE a AND ':notnull' AND b = '"b"' OR b = '"B"';`.

I didn't expect that to work, but is there an emacsql-way of writing `a NOTNULL`, preferably one that works inside `(and ...)`? I also tried `funcall`.

**Comment by skeeto** [comment]
Unfortunately precedence is broken right now and I never gotten around to properly fixing it. See #9.

For weird operators like NOTNULL, the compiler just need to be taught about them. It's "weird" because this unary operator comes *after* the operand. a60deae should address that. Alternatively you could use the [more standard](http://www.postgresql.org/docs/9.1/static/functions-comparison.html) `[... (is a (not nil)))]`.

**Comment by tarsius** [comment]
Thanks for the addition of `notnull`. I think I can live with the lack of precedence for now.

**Comment by tarsius** [comment]
Closing since there's also #9.
