### ISSUE TITLE
[Feature Request] Support LONGVARCHAR type in SQLite

### ISSUE THREAD

**Issue by cireu** [skeeto/emacsql#52]
I try to use emacsql to work with my firefox bookmarks in ff user data sqlite database `$HOME/.mozilla/firefox/*/places.sqlite`. 

However, firefox store bookmark title in `LONGVARCHAR` type instead of `TEXT` type in database and `emacsql-sqlite` program failed to transform SQL query result to Elisp readable text stream.

When I run `emacsql-sqlite` manually and use this query command
```
31SELECT title from moz_bookmarks
```
I found the result was outputed like
```
(Lorem Ipusm)
```

but expect
```
("Lorem Ipsum")
```

Is there any possible way to get `LONGVARCHAR` type data in database?

**Comment by skeeto** [comment]
SQLite doesn't have a LONGVARCHAR type. That's just an alias for TEXT.

The actual problem is that EmacSQL isn't intended to interact with 
arbitrary databases, but rather databases created specifically for/by 
EmacSQL. All text values MUST be in Elisp s-expression form. This will 
not be the case for the Firefox SQLite database.

**Comment by cireu** [comment]
Well, would you give me some suggestions about read data from firefox database?

Should I modified `emacsql-sqlite.c` to add `LONGVARCHAR` type support?

**Comment by skeeto** [comment]
You simply won't be able to use EmacSQL in its current form to do so. 
It's not designed for this use case.

Also, like I said, there's no such thing as LONGVARCHAR in SQLite 
despite what Firefox calls it. It's just an alias for the TEXT affinity:

https://www.sqlite.org/datatype3.html
