### ISSUE TITLE
binary not compiling on windows with clang

### ISSUE THREAD

**Issue by xeijin** [skeeto/emacsql#55]
Hi when I try to compile using `clang` the function exits with `nil` and I get the following in the `compile-log` buffer, any idea what's going wrong?

```
c:/Program Files/LLVM/bin/clang.exe -Ip:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite -O2 -DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_JSON1 -DSQLITE_SOUNDEX p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/sqlite3.c p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/emacsql.c -lm -o p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/emacsql-sqlite.exe
p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/emacsql.c:109:22: warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations]
        int result = scanf("%u ", &length);
                     ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h:1273:20: note: 'scanf' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(scanf_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vcruntime.h:255:55: note: expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vcruntime.h:245:47: note: expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
1 warning generated.
LINK : fatal error LNK1181: cannot open input file 'm.lib'
clang: error: linker command failed with exit code 1181 (use -v to see invocation)
c:/Program Files/LLVM/bin/clang.exe -Ip:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite -O2 -DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_JSON1 -DSQLITE_SOUNDEX p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/sqlite3.c p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/emacsql.c -lm -o p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/emacsql-sqlite.exe
p:/home/.emacs.d/.local/packages/elpa/emacsql-sqlite-20190426.1929/sqlite/emacsql.c:109:22: warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations]
        int result = scanf("%u ", &length);
                     ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h:1273:20: note: 'scanf' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(scanf_s)
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vcruntime.h:255:55: note: expanded from macro '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vcruntime.h:245:47: note: expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
1 warning generated.
LINK : fatal error LNK1181: cannot open input file 'm.lib'
clang: error: linker command failed with exit code 1181 (use -v to see invocation)
```

**Comment by skeeto** [comment]
Most of that is just Visual Studio nonsense, and it looks like it's just 
stuck on the "-lm" argument. None of the supported C implementations on 
Windows actually have a separate math library, so the "-lm" argument 
should be omitted by EmacSQL when compiling for that platform. Mingw-w64 
ships an empty libm just to smooth over this issue.

I'm not really concerned with supporting cl.exe, but I *would* like 
Clang to work even when linking against the Visual Studio standard 
library.

Thank you for reporting this.

**Comment by xeijin** [comment]
OK thanks I wasn't clear but do you plan to fix at all? Would it be as easy as excluding the `-lm` argument?

I don't know much about compiling C programs but the only other alternative to `clang` seems to be using `MSYS2/MiniGW64` - this then creates a dependency on `msys-2.0.dll`. On top of that tools like `gcc.exe` aren't usually in `PATH` on Windows with `MSYS2/MiniGW64` so as well as copying over `msys-2.0.dll` I've had to manually hunt down the executable in `MiniGW64` directory structure which is looking like a very brittle solution. Not to mention this is a multi-gigabyte installation on Windows.

I'm jumping through alot of hoops now just to get `magit` working (having already moved my entire build and install process for emacs to ci/cd on AppVeyor, partly because the computer I run emacs on doesn't have `gcc` and I'm not able to install it). `clang` seems to be alot more straightforward to install, and assuming it can create a statically linked executable, might mean a more portable `emacsql-sqlite.exe` not to mention avoiding the need to download all of `msys2` or `minigw64` -- a fix would be much appreciated!

**Comment by skeeto** [comment]
It should be fixed now, so give it a shot with Clang.

Yeah, don't use an msys2 compiler to build programs you don't intend to 
run "inside" msys2, including Emacs. It's its own, little ecosystem much 
like Cygwin. Though, if you're using Magit and such, you probably *do* 
want to run Emacs from msys2 anyway since it makes everything easier to 
manage. If you don't want to work in msys2, then use a bare-bones 
Mingw-w64 installation (described below) instead when building EmacSQL.

The three major C compilers for Windows are Visual Studio, GCC (via 
MinGW or Mingw-w64, linking against the system's msvcrt.dll), and Clang 
(linking against Visual Studio's standard library). EmacSQL assumes a 
GCC-like interface to the C compiler, so only GCC and Clang are 
supported. Here's a more detailed overview:

Four Ways to Compile C for Windows
https://nullprogram.com/blog/2016/06/13/

What's this MinGW thing about? Well, GCC, as with Clang, is just a 
compiler and doesn't include a C standard library. That's expected to be 
supplied externally. On Linux this is usually done with glibc, though 
there are alternatives like musl. On other unix-like systems it's just 
the system's C standard library.

Until 2015, Windows didn't officially have a system C standard library, 
though there's always been an unofficial, legacy msvcrt.dll in every 
Windows installation for use by drivers and such. As of 2015 there's a 
"Universal CRT" officially installed with Windows, but, in practice, 
it's actually irrelevant to C programs, so you can ignore it.

MinGW, or its more popular fork, Mingw-w64, is a C standard library for 
GCC targeting Windows. Plus it has a full Windows SDK so that the 
programs it builds can call the WinAPI directly. And it has rock-solid 
support for cross-compilation, which is just awesome for me. Most of the 
core functionality is actually in the mentioned msvcrt.dll, but a lot of 
work has gone into wrapping that functionality in a less buggy interface 
that conforms to C99.

The most accessible compiler for EmacSQL on Windows is Mingw-w64. Note: 
That's not MinGW, but Mingw-w64, a confusingly-named fork. Why emphasize 
the fork? Because it's a better quality project. In the "Downloads" 
section of the Mingw-w64 website, the distribution you'd want is 
"MingW-W64-builds". This will give you a simple, no-frills installer 
with no fluff (no msys2, extra tools, etc.). The installation takes 
about a minute and about 500MB of space — bigger than it strictly needs 
to be, but still much smaller than a Visual Studio installation.

Put its "bin" directory in your PATH before running Emacs with EmacSQL 
the first time and then everything will Just Work. Once the binary is 
built, you no longer need gcc in your PATH. The resulting .exe will run 
on any Windows system (with the correct architecture) without any 
dependencies, so you can just move that .exe around wherever you need 
it.

**Comment by xeijin** [comment]
Thanks for the history / explanation of the differences between the compilers - really helpful.

I guess I'm a bit worried about the brittle-ness of the process because for some reason with `mingw-w64` I have to reference a specific folder with version number to use `gcc`, either way that's an issue with my build platform so will figure that out separately.

For anyone else who might stumble across this with the same issue, I use the following command to run the `emacsql-sqlite-ensure-binary` command from a `PowerShell` script:

`emacs --batch -l $env:EMACSDIR/init.el -l emacsql-sqlite --eval --% "(progn (add-to-list 'exec-path \"C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0\") (setenv \"PATH\" (mapconcat #'identity exec-path path-separator)) (emacsql-sqlite-ensure-binary))"`

Note that I add `C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0` to the `exec-path` for just the batch command as I only need the `mingw-w64` binaries temporarily.
