### ISSUE TITLE
Support official sqlite3 executable as backend.

### ISSUE THREAD

**Issue by cireu** [skeeto/emacsql#56]
I'm using `sqlite3` 3.29.0 and findswitch `--batch` will disable readline support, which will be useful in emacsql.

If we can use official sqlite3 executable, it's no need to compile the sqlite client included in emacsql.

**Comment by skeeto** [comment]
This was the original plan back in 2014. The problem is that the 
official command line client is, quite reasonably, not intended to be 
driven interactively by another program popen()-style. It doesn't flush 
often enough, especially when operated in batch mode. Batch mode is for 
scripts that invoke sqlite3 and wait until it exits.

When it's running interactively and doing line flushing, there's a pty 
and readline in the middle, which causes its own nasty effects.

So on Linux it's easy to get into deadlocks where Emacs is waiting on 
sqlite3 while sqlite3 is waiting on Emacs. On Windows it's an impossible 
situation: Linking against MSVCRT means stderr is buffered because, 
well, that's exactly the sort of craziness you get when linking against 
MSVCRT. Deadlocks are immediate and guaranteed.

Here's a thread I made about this stuff at the time:

http://sqlite.1065341.n5.nabble.com/Command-line-shell-not-flushing-stderr-when-interactive-td73340.html

Perhaps the situation has improved. EmacSQL now has a nice test suite 
and generic backend API, so anyone who wants to give it a shot has a 
solid foundation on which to build. Try implementing the cl-generic 
interface on top of the sqlite3 program and see if passes the tests.

**Comment by cireu** [comment]
>  not intended to be
driven interactively by another program popen()-style. It doesn't flush
often enough, especially when operated in batch mode. Batch mode is for
scripts that invoke sqlite3 and wait until it exits.

Now it works perfectly fine, I'm trying to implementing such API.

**Comment by cireu** [comment]
On Wed, 28 Aug 2019 00:48:06 +0800,
Christopher Wellons wrote:
> 
> Hmm, it does seem to work correctly these days on Emacs 26.2 with sqlite 3.27.2:
> 
> (with-temp-buffer
>   (let* ((process-connection-type nil) ; pipe
>          (proc (start-process "sqlite3" (current-buffer)
>                               "sqlite3" "-batch" ":memory:")))
>     (unwind-protect
>         (cl-loop with sql = "select abs(random()) % 1000;\n"
>                  repeat 10
>                  do (process-send-string proc sql)
>                  do (accept-process-output proc)
>                  collect (string-to-number (buffer-string))
>                  do (erase-buffer))
>       (delete-process proc))))
> 
> ;; -> (506 217 198 251 420 284 637 7 260 737)
> 
> ―
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
I just create a new package here https://github.com/cireu/emacsql-sqlite3 ;)
