### ISSUE TITLE
Is dumping of sqlite db supported?

### ISSUE THREAD

**Issue by tarsius** [skeeto/emacsql#66]
If so how and if not could you please implement that?

Currently I resort to closing the db, running `sqlite3 db.sqlite .dump > db.sql` and opening the db again, but that's not very satisfactory.

Thanks for your help!

**Comment by nbfalcon** [comment]
@tarsis The [`sqlite_master`](https://www.techonthenet.com/sqlite/sys_tables/index.php) table contains a list of all tables, and you could use that + [`PRAGMA table_info`](https://www.sqlite.org/pragma.html#pragma_table_info) to derive their schemae. And you could of course dump the tables. The `.dump` command isn't support directly, since it is an sqlite-shell (the executable)-specific extension, not present in the library (although not too complex).

**Comment by nbfalcon** [comment]
Actually, this will probably not work due to the output being `read`. However, [sqlite supports concurrent access](https://sqlite.org/lockingv3.html), so the DB connection needn't be closed.

**Comment by tarsius** [comment]
> the DB connection needn't be closed.

I am stopped doing that and so far it doesn't seem to cause any issues.
